package main

import (
	"flag"
	"fmt"
	"os"
	"time"

	"github.com/gossie/aoc-generator/day"
	"github.com/gossie/aoc-generator/year"
)

var descriptions = map[string]string{
	"generate": "Generates a new directory for your advent of code project.",
	"create":   "Creates a scaffold for the tasks of a single day. This command needs to be called within the directory generated by 'aic generate ...'.",
}

func main() {
	generateCmd := flag.NewFlagSet("generate", flag.ExitOnError)
	aocYear := generateCmd.Int("year", time.Now().Year(), "The year the project is used for")
	language := generateCmd.String("language", "", "The programming language you are using (currently supported are go and java)")
	githubUser := generateCmd.String("githubUser", "", "Your GitHub username (only used for the go module)")

	createDayCmd := flag.NewFlagSet("create", flag.ExitOnError)
	aocDay := createDayCmd.Int("day", time.Now().Day(), "The day you want to implement the task for")

	defer func() {
		if r := recover(); r != nil {
			fmt.Println("Something went terribly wrong:", r)
			fmt.Println("This is how the aoc command is to be used:")
			fmt.Println()
			printHelp([]*flag.FlagSet{generateCmd, createDayCmd})
		}
	}()

	command := os.Args[1]
	switch command {
	case "generate":
		handleGenerate(generateCmd, aocYear, language, githubUser)
	case "create":
		handleCreateDay(createDayCmd, aocDay)
	case "--help":
		printHelp([]*flag.FlagSet{generateCmd, createDayCmd})
	default:
		printHelp([]*flag.FlagSet{generateCmd, createDayCmd})
	}
}

func handleGenerate(generateCmd *flag.FlagSet, aocYear *int, language, githubUser *string) {
	generateCmd.Parse(os.Args[2:])
	if *language == "go" && *githubUser == "" {
		fmt.Println("I need the GitHub username to create a go module")
		os.Exit(1)
	}
	year.InitializeYear(*aocYear, *language, *githubUser)
}

func handleCreateDay(createDayCmd *flag.FlagSet, aocDay *int) {
	createDayCmd.Parse(os.Args[2:])
	day.CreateDay(*aocDay)
}

func printHelp(commands []*flag.FlagSet) {
	fmt.Println("Use aoc to generate scaffolds for your advent of code go project.")
	fmt.Println()
	for _, cmd := range commands {
		fmt.Println(cmd.Name(), ":", descriptions[cmd.Name()])
		cmd.PrintDefaults()
		fmt.Println()
	}
}
